*&---------------------------------------------------------------------*
*&  Include           ZEDR05_20230522_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  SELECT-OPTIONS : S_ZEMPNO FOR GS_INFO_JOIN-ZEMPNO.
  SELECT-OPTIONS : S_ZDATE FOR GS_INFO_JOIN-ZFRDATE NO INTERVALS NO-EXTENSION.
  SELECT-OPTIONS : S_ZDEPT FOR GS_INFO_JOIN-ZDEPTNR NO INTERVALS NO-EXTENSION.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  PARAMETERS : P_CHECK AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B2.