*&---------------------------------------------------------------------*
*&  Include           ZEDR05_20230522_TOP
*&---------------------------------------------------------------------*

RANGES : R_FG FOR ZWORK05_001_1_1-ZRETIRE_FG.

DATA : BEGIN OF GS_INFO_JOIN,
         ICON       TYPE C LENGTH 4,
         ZEMPNO     LIKE ZWORK05_001_1_1-ZEMPNO, "사원번호
         ZEMPNAME   LIKE ZWORK05_001_1_2-ZEMPNAME, "사원명
         ZDEPTNR    LIKE ZWORK05_001_1_1-ZDEPTNR, "부서코드
         ZDEPTNAME  LIKE ZWORK05_001_S1-ZDEPTNAME, " 부서명
         ZFRDATE    LIKE ZWORK05_001_1_1-ZFRDATE, "시작 유효기간
         ZTODATE    LIKE ZWORK05_001_1_1-ZTODATE, "끝 유효기간
         ZRANKCODE  LIKE ZWORK05_001_1_1-ZRANKCODE, ""직급코드
         ZRANKNAME  LIKE ZWORK05_001_S3-ZRANKNAME, "직급명
         ZGENDER    LIKE ZWORK05_001_1_2-ZGENDER, "성별
         ZGUBUNNAME TYPE C LENGTH 4, "성별 이름
         ZEMPDATE   LIKE ZWORK05_001_1_1-ZEMPDATE, "입사일자
         ZADDRESS   LIKE ZWORK05_001_1_2-ZADDRESS, "주소
         ZRETDATE   LIKE ZWORK05_001_1_1-ZRETDATE, "퇴사일자
         ZRETIRE_FG LIKE ZWORK05_001_1_1-ZRETIRE_FG, "퇴사상태
       END OF GS_INFO_JOIN.
DATA : GT_INFO_JOIN LIKE TABLE OF GS_INFO_JOIN.


DATA : BEGIN OF GS_SAL1,
         ZEMPNO       LIKE ZWORK05_001_2-ZEMPNO, "사원번호
         ZDEPTNR      LIKE ZWORK05_001_1_1-ZDEPTNR, "부서코드
         ZCONTYEAR    LIKE ZWORK05_001_2-ZCONTYEAR, "계약연도
         ZCONTSTDATE  LIKE ZWORK05_001_2-ZCONTSTDATE, "계약시작
         ZCONTENDDATE LIKE ZWORK05_001_2-ZCONTENDDATE, "계약종료
         ZCONTAMT     LIKE ZWORK05_001_2-ZCONTAMT, "계약금액
         ZBANKNR      LIKE ZWORK05_001_2-ZBANKNR, "은행코드
         ZAMTNR       LIKE ZWORK05_001_2-ZAMTNR, "계좌번호
       END OF GS_SAL1.
DATA : GT_SAL1 LIKE TABLE OF GS_SAL1.

DATA : BEGIN OF GS_EVAL,
         ZEMPNO      LIKE ZWORK05_001_3-ZEMPNO, "사원번호
         ZDEPTNR     LIKE ZWORK05_001_3-ZDEPTNR, "부서코드
         ZEVALYEAR   LIKE ZWORK05_001_3-ZEVALYEAR, "평가연도
         ZEVALDATEFR LIKE ZWORK05_001_3-ZEVALDATEFR, "평가기간 시작
         ZEVALDATETO LIKE ZWORK05_001_3-ZEVALDATETO, "평가기간 종료
         ZEVALRANK   LIKE ZWORK05_001_3-ZEVALRANK, "평가 등급
       END OF GS_EVAL.
DATA : GT_EVAL LIKE TABLE OF GS_EVAL.

DATA : BEGIN OF GS_AUTHO,
         ZID     LIKE ZWORK05_001_5-ZID, "회원 아이디
         ZFRDATE LIKE ZWORK05_001_5-ZFRDATE, "유효기간 시작
         ZTODATE LIKE ZWORK05_001_5-ZTODATE, "유효기간 종료
         ZLEVEL1 LIKE ZWORK05_001_5-ZLEVEL1, "레벨1
         ZLEVEL2 LIKE ZWORK05_001_5-ZLEVEL2, "레벨2
       END OF GS_AUTHO.
DATA : GT_AUTHO LIKE TABLE OF GS_AUTHO.

DATA : BEGIN OF GS_RESULT1,
         ICON       TYPE C LENGTH 4,
         ZEMPNO     LIKE ZWORK05_001_1_1-ZEMPNO, "사원번호
         ZEMPNAME   LIKE ZWORK05_001_1_2-ZEMPNAME, "사원명
         ZDEPTNAME  LIKE ZWORK05_001_S1-ZDEPTNAME, " 부서명
         ZFRDATE    LIKE ZWORK05_001_1_1-ZFRDATE, "시작 유효기간
         ZTODATE    LIKE ZWORK05_001_1_1-ZTODATE, "끝 유효기간
         ZRANKNAME  LIKE ZWORK05_001_S3-ZRANKNAME, "직급명
         ZGUBUNNAME TYPE C LENGTH 4,
         ZEMPDATE   LIKE ZWORK05_001_1_1-ZEMPDATE, "입사일자
         ZADDRESS   LIKE ZWORK05_001_1_2-ZADDRESS, "주소
         ZRETDATE   LIKE ZWORK05_001_1_1-ZRETDATE, "퇴사일자
         ZRETIRE_FG LIKE ZWORK05_001_1_1-ZRETIRE_FG, "퇴사상태
       END OF GS_RESULT1.
DATA : GT_RESULT1 LIKE TABLE OF GS_RESULT1.

DATA : BEGIN OF GS_RESULT2,
         ZEMPNO      LIKE ZWORK05_001_3-ZEMPNO, "사원번호
         ZDEPTNAME   LIKE ZWORK05_001_S1-ZDEPTNAME, " 부서명
         ZEVALYEAR   LIKE ZWORK05_001_3-ZEVALYEAR, "평가연도
         ZEVALDATEFR LIKE ZWORK05_001_3-ZEVALDATEFR, "평가기간 시작
         ZEVALDATETO LIKE ZWORK05_001_3-ZEVALDATETO, "평가기간 종료
         ZEVALRANK   LIKE ZWORK05_001_3-ZEVALRANK, "평가 등급
       END OF GS_RESULT2.
DATA : GT_RESULT2 LIKE TABLE OF GS_RESULT2.

DATA : BEGIN OF GS_RESULT3,
         ZEMPNO       LIKE ZWORK05_001_2-ZEMPNO, "사원번호
         ZCONTYEAR    LIKE ZWORK05_001_2-ZCONTYEAR, "계약연도
         ZCONTSTDATE  LIKE ZWORK05_001_2-ZCONTSTDATE, "계약시작
         ZCONTENDDATE LIKE ZWORK05_001_2-ZCONTENDDATE, "계약종료
         ZCONTAMT     LIKE ZWORK05_001_2-ZCONTAMT, "계약금액
         ZBANKNAME    LIKE ZWORK05_001_S4-ZBANKNAME, "은행명
         ZAMTNR       LIKE ZWORK05_001_2-ZAMTNR, "계좌번호
       END OF GS_RESULT3.

DATA : GT_RESULT3 LIKE TABLE OF GS_RESULT3.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.

DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
       GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER,
       GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER,
       GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER,
       GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER.

DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID,
       GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID,
       GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GS_FIELDCAT  TYPE LVC_S_FCAT,
       GT_FIELDCAT1 TYPE LVC_T_FCAT,
       GT_FIELDCAT2 TYPE LVC_T_FCAT,
       GT_FIELDCAT3 TYPE LVC_T_FCAT.

DATA : GS_SORT  TYPE LVC_S_SORT,
       GT_SORT1 TYPE LVC_T_SORT,
       GT_SORT2 TYPE LVC_T_SORT,
       GT_SORT3 TYPE LVC_T_SORT.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_VARIANT TYPE DISVARIANT.